version: "3.2"
services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/todo-app/frontend
      - /todo-app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm start